spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tranvanson231099@gmail.com
    password: oflbomfuiypfboyg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true