spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 4cf99f63c69a80407a0e
            client-secret: 4e908f9d4cf35e347651e298216a244e25645594
          google:
            client-id: 207549995526-54ei4m6e3d2uk59dmhcj05k5cr3868n6.apps.googleusercontent.com
            client-secret: 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

frontend:
  url: http://localhost:3000
