# Database configuration properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webdemo?createDatabaseIfNotExist=true
    username: root
    # password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    

  # Hibernate properties
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
